export const Users = [
    {
        id:1,
        profilePicture:"assets/person/2.jpg",
        username:"Jessica",
    },
    {
        id:2,
        profilePicture:"assets/person/3.jpg",
        username:"Madline",
    },
    {
        id:3,
        profilePicture:"assets/person/4.jpg",
        username:"Paul",
    },
    {
        id:4,
        profilePicture:"assets/person/5.jpg",
        username:"Cristena",
    },
    {
        id:5,
        profilePicture:"assets/person/6.jpg",
        username:"Jullia",
    },
    {
        id:6,
        profilePicture:"assets/person/7.jpg",
        username:"Micheal",
    },
    {
        id:7,
        profilePicture:"assets/person/8.jpg",
        username:"John",
    },
    {
        id:8,
        profilePicture:"assets/person/9.jpg",
        username:"Harry",
    },
    {
        id:9,
        profilePicture:"assets/person/10.jpg",
        username:"Adam",
    },
];

export const Posts = [
    {
        id:1,
        desc:"Dogs are so friendly and faithful",
        photo:"assets/posts/1.jpg",
        date:"5 mins ago",
        userId:1,
        like:32,
        comments:9,
    },
    {
        id:2,
        desc:"Paris Is The City Of Love",
        photo:"assets/posts/2.jpg",
        date:"15 mins ago",
        userId:2,
        like:2,
        comments:1,
    },
    {
        id:3,
        desc:"Coffee Is An Addiction",
        photo:"assets/posts/3.jpg",
        date:"1 hour ago",
        userId:3,
        like:61,
        comments:2,
    },
    {
        id:4,
        desc:"Eat Healthy, Be Healthy",
        photo:"assets/posts/4.jpg",
        date:"4 hours ago",
        userId:4,
        like:7,
        comments:3,
    },
    {
        id:5,
        desc:"Enjoy The Beauty Of Nature",
        photo:"assets/posts/5.jpg",
        date:"5 hours ago",
        userId:5,
        like:23,
        comments:5,
    },
    {
        id:6,
        desc:"Enjoy The Beautiful Sunset",
        photo:"assets/posts/6.jpg",
        date:"1 day ago",
        userId:6,
        like:44,
        comments:6,
    },
    {
        id:7,
        desc:"Feel Some Peace With Nature",
        photo:"assets/posts/7.jpg",
        date:"2 days ago",
        userId:7,
        like:52,
        comments:3,
    },
    {
        id:8,
        desc:"Girrafes Are So Funny Animals",
        photo:"assets/posts/8.jpg",
        date:"3 days ago",
        userId:8,
        like:15,
        comments:1,
    },
    {
        id:9,
        desc:"Let's Make Some Noise",
        photo:"assets/posts/9.jpg",
        date:"5 days ago",
        userId:9,
        like:11,
        comments:2,
    },
]